export const WebSearchTopics = {
  'News and Current Events': [
    'Latest news in the USA',
    'Current events around the world',
    'Breaking news today',
    'Top news stories this week',
    'Recent updates on [specific event]',
    'Political news headlines',
    'Sports news highlights',
    'Technology news updates',
    'Entertainment news today',
    'Business news reports',
  ],
  'Shopping and Fashion': [
    "Latest men's wear trends",
    'Best online shopping sites',
    "Women's fashion trends 2024",
    'Top-rated beauty products',
    'Popular electronic gadgets',
    'New arrivals in clothing',
    'Discounted designer brands',
    'Best places to buy Adidas shoes',
    'Reviews of Dior products',
    'Affordable luxury watches',
  ],
  'Technology and Gadgets': [
    'Latest smartphone releases',
    'Top tech companies in the world',
    'Best laptops for work and play',
    'New gaming consoles 2024',
    'Reviews of new gadgets',
    'Upcoming technology trends',
    'Best apps for productivity',
    'Popular smart home devices',
    'Comparison of iPhone vs. Samsung',
    'Latest software updates',
  ],
  'Health and Wellness': [
    'Best fitness routines for 2024',
    'Healthy diet plans',
    'Top wellness retreats',
    'Mental health resources',
    'Natural remedies for common ailments',
    'Latest medical research',
    'Effective weight loss programs',
    'Benefits of yoga and meditation',
    'Popular health supplements',
    'Skin care tips and advice',
  ],
  'Travel and Tourism': [
    'Top travel destinations 2024',
    'Best places to visit in Italy',
    'Budget-friendly vacation spots',
    'Travel tips and hacks',
    'Reviews of popular hotels and resorts',
    'Best travel agencies',
    'Adventure travel destinations',
    'Luxury cruises 2024',
    'Family-friendly vacation ideas',
    'Latest travel advisories',
  ],
  'Education and Learning': [
    'Best online learning platforms',
    'Top universities in the world',
    'Free online courses',
    'Educational resources for kids',
    'Study tips for students',
    'Career development programs',
    'Language learning apps',
    'Scholarships for international students',
    'Professional certification courses',
    'Continuing education opportunities',
  ],
  'Business and Finance': [
    'Top website development companies',
    'Best investment strategies',
    'Small business tips',
    'Latest market trends',
    'Financial planning advice',
    'Popular startup ideas',
    'Reviews of business software',
    'Tips for online marketing',
    'Best credit cards 2024',
    'Tax planning strategies',
  ],
  'Home and Garden': [
    'Home decor ideas',
    'Best furniture stores',
    'Latest interior design trends',
    'DIY home improvement projects',
    'Gardening tips and tricks',
    'Smart home technology',
    'Reviews of home appliances',
    'Top-rated kitchen gadgets',
    'Energy-efficient home solutions',
    'Outdoor living space ideas',
  ],
};
