export const WebSearchTopics = {
  'News and Current Events': [
    'Latest news in the USA',
    'Current events around the world',
    'Breaking news today',
    'Top news stories this week',
    'Recent updates on COVID-19',
    'Political news headlines',
    'Sports news highlights',
    'Technology news updates',
    'Entertainment news today',
    'Business news reports',
    'Weather forecast for the week',
    'Local news in your area',
    'Celebrity gossip and rumors',
    'Stock market news',
    'Science and health news',
    'Educational news articles',
    'Travel advisories and alerts',
    'Crime reports and investigations',
    'Environmental news updates',
    'Human interest stories',
  ],
  'Shopping and Fashion': [
    "Latest men's wear trends",
    'Best online shopping sites',
    "Women's fashion trends 2024",
    'Top-rated beauty products',
    'Popular electronic gadgets',
    'New arrivals in clothing',
    'Discounted designer brands',
    'Best places to buy Adidas shoes',
    'Reviews of Dior products',
    'Affordable luxury watches',
    'Fashion tips and advice',
    'Shopping hacks and deals',
    'Trendy accessories for 2024',
    'Stylish home decor items',
    'Seasonal fashion trends',
    'Fashion shows and events',
    'Celebrity fashion styles',
    'Fashion industry news',
    'Fashion photography inspiration',
  ],
  'Technology and Gadgets': [
    'Latest smartphone releases',
    'Top tech companies in the world',
    'Best laptops for work and play',
    'New gaming consoles 2024',
    'Reviews of new gadgets',
    'Upcoming technology trends',
    'Best apps for productivity',
    'Popular smart home devices',
    'Comparison of iPhone vs. Samsung',
    'Latest software updates',
    'Tech tutorials and guides',
    'Innovative tech startups',
    'Tech industry news',
    'Cybersecurity tips and advice',
    'Artificial intelligence developments',
    'Virtual reality and augmented reality',
    'Internet of Things (IoT) devices',
    'Tech events and conferences',
    'Tech podcasts and YouTube channels',
  ],
  'Health and Wellness': [
    'Best fitness routines for 2024',
    'Healthy diet plans',
    'Top wellness retreats',
    'Mental health resources',
    'Natural remedies for common ailments',
    'Latest medical research',
    'Effective weight loss programs',
    'Benefits of yoga and meditation',
    'Popular health supplements',
    'Skin care tips and advice',
    'Reviews of fitness equipment',
    'Healthy recipes for every meal',
    'Tips for better sleep',
    'Health and wellness apps',
    'Personal development strategies',
    'Alternative medicine practices',
    'Fitness challenges and trends',
    'Wellness products and services',
    'Healthcare industry news',
  ],
  'Travel and Tourism': [
    'Top travel destinations 2024',
    'Best places to visit in Italy',
    'Budget-friendly vacation spots',
    'Travel tips and hacks',
    'Reviews of popular hotels and resorts',
    'Best travel agencies',
    'Adventure travel destinations',
    'Luxury cruises 2024',
    'Family-friendly vacation ideas',
    'Latest travel advisories',
    'Travel insurance options',
    'Cultural experiences around the world',
    'Travel photography inspiration',
    'Travel vlogs and blogs',
    'Travel deals and discounts',
    'Solo travel tips and advice',
    'Sustainable travel initiatives',
    'Travel industry news',
    'Travel gadgets and accessories',
  ],
  'Education and Learning': [
    'Best online learning platforms',
    'Top universities in the world',
    'Free online courses',
    'Educational resources for kids',
    'Study tips for students',
    'Career development programs',
    'Language learning apps',
    'Scholarships for international students',
    'Professional certification courses',
    'Continuing education opportunities',
    'Educational technology trends',
    'Reviews of educational software',
    'Teaching strategies and resources',
    'Educational podcasts and YouTube channels',
    'Educational news and updates',
    'Learning challenges and solutions',
    'Educational events and conferences',
    'Educational research and studies',
    'Educational policy and reform',
  ],
  'Business and Finance': [
    'Top website development companies',
    'Best investment strategies',
    'Small business tips',
    'Latest market trends',
    'Financial planning advice',
    'Popular startup ideas',
    'Reviews of business software',
    'Tips for online marketing',
    'Best credit cards 2024',
    'Tax planning strategies',
    'Entrepreneurship resources',
    'Business success stories',
    'Business events and conferences',
    'Business industry news',
    'Financial literacy programs',
    'Real estate market updates',
    'Stock market analysis',
    'Cryptocurrency trends',
    'Personal finance tips',
  ],
  'Home and Garden': [
    'Home decor ideas',
    'Best furniture stores',
    'Latest interior design trends',
    'DIY home improvement projects',
    'Gardening tips and tricks',
    'Smart home technology',
    'Reviews of home appliances',
    'Top-rated kitchen gadgets',
    'Energy-efficient home solutions',
    'Outdoor living space ideas',
    'Home organization hacks',
    'Home cleaning tips',
    'Home renovation inspiration',
    'Home security systems',
    'Home maintenance guides',
    'Garden landscaping ideas',
    'Home and garden events',
    'Home and garden industry news',
    'Home and garden podcasts',
  ],
};
