export const WebSearchTopics = {
  'News and Current Events': [
    'Latest world news',
    'Breaking news headlines',
    'Current events in the US',
    'Top news stories today',
    'Political news updates',
    'Economic news and analysis',
    'Technology news updates',
    'Health and science news',
    'Sports news highlights',
    'Entertainment news and gossip',
    'Weather news and forecasts',
    'Global news coverage',
    'US news headlines',
    'Local news updates',
    'Business news and trends',
    'Financial news and reports',
    'Top news websites',
    'Best news apps',
    'International news highlights',
    'News analysis and opinions',
    'Current affairs programs',
    'Breaking news alerts',
    'Top news anchors',
    'Investigative journalism',
    'News podcasts to follow',
    'Top news magazines',
    'News on social media',
    'News aggregator websites',
    'Political analysis shows',
    'Live news streaming',
    'News coverage on climate change',
    'Science and innovation news',
    'Technology and gadget news',
    'Cultural news and events',
    'Celebrity news and updates',
    'Daily news briefings',
    'Weekly news roundups',
    'Monthly news digests',
    'News commentary and debates',
    'Opinion pieces and editorials',
    'Global conflict news',
    'Natural disaster updates',
    'News on international relations',
    'Election news and results',
    'Public policy news',
    'Education news and reforms',
    'Healthcare news and developments',
    'Environmental news reports',
    'Energy sector news',
    'Infrastructure news updates',
    'News on social issues',
    'Crime and justice news',
    'Immigration news and policies',
    'News on civil rights',
    'Military news and updates',
    'Technology policy news',
    'Space exploration news',
    'Science discoveries',
    'Cultural heritage news',
    'Art and entertainment news',
    'Travel news and tips',
    'Food and lifestyle news',
    'Fashion industry news',
    'Automotive news and trends',
    'Real estate news updates',
    'Agriculture news',
    'Retail industry news',
    'Aviation news and updates',
    'Maritime news',
    'News on artificial intelligence',
    'Blockchain and cryptocurrency news',
    'Cybersecurity news',
    'Biotechnology news',
    'Pharmaceutical news',
    'Renewable energy news',
    'Telecommunication news',
    'Gaming industry news',
    'Streaming services news',
    'Music industry updates',
    'Film and TV news',
    'Book and literary news',
    'Theater and performing arts news',
    'Museum and exhibition news',
    'Festival news and updates',
    'News on international trade',
    'Tariffs and trade policies',
    'Startup news and trends',
    'Venture capital news',
    'Stock market news',
    'Commodities news',
    'Economic indicators',
    'Employment and labor news',
    'Consumer news and reports',
    'Global health news',
    'Pandemic news and updates',
    'Vaccine news and research',
    'Mental health news',
    'News on genetic research',
    'Public health policies',
    'Epidemiology news',
  ],
  'Shopping and Fashion': [
    'Best online clothing stores',
    'Top fashion trends 2024',
    'Affordable fashion brands',
    'Luxury fashion brands',
    'Best places to buy shoes online',
    'Top handbag brands',
    'Best sustainable fashion brands',
    "Top men's fashion trends",
    "Best women's fashion trends",
    'Top fashion influencers',
    'Best fashion blogs',
    'Top fashion magazines',
    'Best fashion subscription boxes',
    'Top online fashion deals',
    'Best places to buy jewelry online',
    'Top streetwear brands',
    'Best vintage clothing stores',
    'Top online boutiques',
    'Best places to buy workout clothes',
    'Top swimwear brands',
    'Best places to buy accessories',
    'Top fashion apps',
    'Best places to buy winter coats',
    'Top activewear brands',
    'Best places to buy formal wear',
    'Top fashion designers',
    'Best plus-size fashion brands',
    'Top fashion events and shows',
    'Best maternity clothing stores',
    'Top fashion YouTube channels',
    'Best places to buy dresses',
    'Top eyewear brands',
    'Best places to buy denim',
    'Top casual wear brands',
    'Best fashion podcasts',
    'Top sustainable shopping tips',
    'Best fashion documentaries',
    'Top ethical fashion brands',
    'Best places to buy hats',
    'Top eco-friendly fashion brands',
    'Best places to buy scarves',
    'Top footwear brands',
    'Best places to buy lingerie',
    'Top outerwear brands',
    'Best places to buy watches',
    'Top fashion tips and hacks',
    'Best places to buy suits',
    'Top fashion trends for teens',
    "Best children's clothing stores",
    'Top fashion schools',
    'Best places to buy sunglasses',
    'Top fashion accessories',
    'Best places to buy sportswear',
    'Top fashion icons',
    'Best fashion TV shows',
    'Top designer collaborations',
    'Best places to buy handbags',
    'Top seasonal fashion trends',
    'Best places to buy beachwear',
    'Top athleisure brands',
    'Best places to buy socks',
    'Top workwear brands',
    'Best places to buy T-shirts',
    'Top fashion marketplaces',
    'Best vintage fashion finds',
    'Top fashion newsletters',
    'Best fast fashion brands',
    'Top fashion styling tips',
    'Best places to buy belts',
    'Top resort wear brands',
    'Best fashion Instagram accounts',
    'Top fashion tech innovations',
    'Best places to buy jumpsuits',
    'Top fashion photography tips',
    'Best places to buy skirts',
    'Top minimalist fashion brands',
    'Best places to buy blouses',
    'Top avant-garde fashion brands',
    'Best places to buy sweaters',
    'Top fashion resale sites',
    'Best fashion online courses',
    'Top capsule wardrobe tips',
    'Best places to buy pants',
    'Top fashion gift ideas',
    'Best places to buy blazers',
    'Top gender-neutral fashion brands',
    'Best places to buy cardigans',
    'Top fashion trend predictions',
    'Best places to buy coats',
    'Top fashion industry news',
    'Best fashion books',
    'Top fashion editorials',
    'Best places to buy gloves',
    'Top sustainable fashion tips',
    'Best places to buy underwear',
    'Top festival fashion trends',
    'Best fashion TV channels',
    'Top fashion startup ideas',
    'Best places to buy pajamas',
    'Top high fashion brands',
    'Best fashion travel destinations',
  ],
  'Technology and Gadgets': [
    'Best smartphones of 2024',
    'Top laptop brands',
    'Latest technology trends',
    'Best budget gadgets',
    'Reviews of smart home devices',
    'Best fitness trackers',
    'Top gaming consoles',
    'VR headset reviews',
    'Best noise-canceling headphones',
    'Top wireless earbuds',
    'Best tablets for students',
    'Top smartwatches',
    'Best drones for photography',
    'Top e-readers',
    'Best streaming devices',
    'Top 4K TVs',
    'Best computer monitors',
    'Top tech accessories',
    'Best external hard drives',
    'Top wireless chargers',
    'Best Bluetooth speakers',
    'Top home security systems',
    'Best portable power banks',
    'Top smart home hubs',
    'Best gaming laptops',
    'Top AI-powered gadgets',
    'Best tech gifts',
    'Top home automation devices',
    'Best video doorbells',
    'Top smart thermostats',
    'Best robot vacuums',
    'Top smart kitchen gadgets',
    'Best wearable tech',
    'Top tech startups to watch',
    'Best electric scooters',
    'Top tech innovations',
    'Best budget smartphones',
    'Top noise-canceling earbuds',
    'Best streaming services',
    'Top tech for remote work',
    'Best projectors for home theater',
    'Top fitness apps',
    'Best mobile payment apps',
    'Top tech news websites',
    'Best cloud storage services',
    'Top video conferencing tools',
    'Best smart light bulbs',
    'Top tech podcasts',
    'Best tech YouTube channels',
    'Top tech events and conferences',
    'Best gaming headsets',
    'Top tech blogs to follow',
    'Best photo editing software',
    'Top tech influencers',
    'Best educational tech tools',
    'Top virtual assistants',
    'Best 3D printers',
    'Top smart health devices',
    'Best wireless keyboards',
    'Top tech deals',
    'Best ergonomic tech accessories',
    'Top electric bikes',
    'Best antivirus software',
    'Top VPN services',
    'Best tech for travel',
    'Top digital cameras',
    'Best online backup services',
    'Top music streaming services',
    'Best productivity apps',
    'Top home theater systems',
    'Best car gadgets',
    'Top podcast apps',
    'Best online learning platforms',
    'Top tech repair services',
    'Best smart speakers',
    'Top tech for kids',
    'Best coding platforms',
    'Top tech subscription boxes',
    'Best password managers',
    'Top tech for seniors',
    'Best smart mirrors',
    'Top virtual reality games',
    'Best tech for fitness enthusiasts',
    'Top tech for pet owners',
    'Best AI tools',
    'Top noise-canceling headphones',
    'Best smart scales',
    'Top fitness trackers',
    'Best budget earbuds',
    'Top high-end smartphones',
    'Best electric vehicles',
    'Top tech for small businesses',
    'Best tech for gamers',
    'Top tech for productivity',
    'Best smart displays',
    'Top tech for home offices',
    'Best smart plugs',
    'Top augmented reality apps',
    'Best health monitoring devices',
    'Top tech for outdoor enthusiasts',
    'Best tech for music lovers',
  ],
  'Health and Wellness': [
    'Healthy living tips',
    'Best diets for weight loss',
    'Fitness and exercise routines',
    'Mental health awareness',
    'Stress management techniques',
    'Healthy eating habits',
    'Benefits of yoga',
    'Home workout ideas',
    'Meditation practices',
    'Holistic health approaches',
    'Nutritional advice',
    'Sleep improvement tips',
    'Natural remedies for common ailments',
    'Wellness retreats',
    'Mental wellness resources',
    'Healthy recipes',
    'Benefits of staying hydrated',
    'Importance of regular check-ups',
    'Immunity-boosting foods',
    'Heart health tips',
    'Mindfulness practices',
    'Detox diets and benefits',
    'Health benefits of probiotics',
    'Personal wellness plans',
    'Guide to vitamins and supplements',
    'Chronic illness management',
    'Healthy aging tips',
    'Work-life balance strategies',
    'Impact of exercise on mental health',
    'Reducing sugar intake',
    'Healthy snack ideas',
    'Fitness trackers and apps',
    'Alternative medicine',
    'Benefits of regular physical activity',
    'Skin care routines',
    'Understanding mental disorders',
    'Tips for quitting smoking',
    'Health benefits of herbal teas',
    'Gut health and diet',
    'Daily wellness routines',
    'Importance of a balanced diet',
    'Self-care practices',
    'Hydration and health',
    'Managing anxiety and depression',
    'Healthy lifestyle changes',
    'Holistic nutrition',
    'Importance of fiber',
    'Health benefits of meditation',
    'Stress-relief activities',
    'Weight management strategies',
    'Healthy family meals',
    'Fitness challenges',
    'Sleep hygiene tips',
    'Mental resilience techniques',
    'Superfoods to include in diet',
    'Wellness apps and tools',
    'Preventive healthcare tips',
    'Healthy cooking methods',
    'Positive thinking and health',
    'Health benefits of regular walks',
    'Essential oils and their uses',
    'Managing chronic pain',
    'Healthy work environment tips',
    'Diet and mental health',
    'Posture and back health',
    'Benefits of plant-based diets',
    'Cardio exercises for beginners',
    'Healthy breakfast ideas',
    'Health risks of processed foods',
    'Improving digestion naturally',
    'Dental health tips',
    'Healthy meal planning',
    'Relaxation techniques',
    'Understanding food labels',
    'Benefits of intermittent fasting',
    'Physical activity guidelines',
    'Balanced diet for children',
    'Mental health support groups',
    'Wellness products reviews',
    'Guide to healthy fats',
    'Maintaining bone health',
    'Health benefits of laughter',
    'Overcoming fitness plateaus',
    'Healthy holiday eating',
    'Importance of mental breaks',
    'Managing screen time',
    'Health and wellness books',
    'Tips for healthy joints',
    'Healthy grocery shopping',
    'Wellness for seniors',
    'Health benefits of stretching',
    'Workouts for busy schedules',
    'Health benefits of cycling',
    'Positive impact of hobbies',
    'Healthy living blogs',
    'Mental health in the workplace',
    'Health benefits of dancing',
    'Clean eating principles',
    'Tips for healthy skin',
    'Health risks of sedentary lifestyle',
    'Essential nutrients for the body',
  ],
  'Travel and Tourism': [
    'Top travel destinations 2024',
    'Best places to visit in Italy',
    'Budget-friendly vacation spots',
    'Travel tips and hacks',
    'Reviews of popular hotels and resorts',
    'Best travel agencies',
    'Adventure travel destinations',
    'Luxury cruises 2024',
    'Family-friendly vacation ideas',
    'Latest travel advisories',
    'Travel insurance options',
    'Cultural experiences around the world',
    'Travel photography inspiration',
    'Travel vlogs and blogs',
    'Travel deals and discounts',
    'Solo travel tips and advice',
    'Sustainable travel initiatives',
    'Travel industry news',
    'Travel gadgets and accessories',
  ],
  'Education and Learning': [
    'Best online learning platforms',
    'Top universities in the world',
    'Free online courses',
    'Educational resources for kids',
    'Study tips for students',
    'Career development programs',
    'Language learning apps',
    'Scholarships for international students',
    'Professional certification courses',
    'Continuing education opportunities',
    'Educational technology trends',
    'Reviews of educational software',
    'Teaching strategies and resources',
    'Educational podcasts and YouTube channels',
    'Educational news and updates',
    'Learning challenges and solutions',
    'Educational events and conferences',
    'Educational research and studies',
    'Educational policy and reform',
    'Homeschooling curriculum and resources',
    'Early childhood education strategies',
    'Gifted and talented education programs',
    'Special education resources and support',
    'The history of education',
    'Philosophy of education',
    'The science of learning',
    'Memory improvement techniques',
    'Speed reading strategies',
    'Critical thinking skills development',
    'Problem-solving skills development',
    'Effective communication skills for students',
    'Time management for students',
    'Motivation and self-discipline for learners',
    'Overcoming test anxiety',
    'Online learning vs traditional learning',
    'The future of education',
    'Artificial intelligence in education',
    'Virtual reality and augmented reality in learning',
    'Personalized learning experiences',
    'The role of parents in education',
    'Teacher training and development programs',
    'Assessment and evaluation in education',
    'Educational equity and inclusion',
    'Combating educational inequality',
    'Education for sustainable development',
    'Global citizenship education',
    'Learning a new language at any age',
    'The benefits of lifelong learning',
    'Learning through play and exploration',
    'Unconventional learning methods',
    'The importance of creativity in education',
    'Developing emotional intelligence in children',
    'Mindfulness and meditation for students',
    'Building resilience in learners',
    'The importance of physical activity in learning',
    'Nutrition and its impact on learning',
    'The role of technology in the classroom',
    'Cyberbullying prevention in schools',
    'Digital citizenship education',
    'Online safety for students',
    'Distance learning strategies and resources',
    'Blended learning models',
    'Flipped classroom approach',
    'Project-based learning',
    'Problem-based learning',
    'Inquiry-based learning',
    'Gamification in education',
    'Creating a positive learning environment',
    'Building strong teacher-student relationships',
    'The importance of student feedback',
    'Self-directed learning strategies',
    'Developing independent learning skills',
    'The benefits of extracurricular activities',
    'Choosing the right college or university',
    'Student loan options and repayment strategies',
    'Financial aid for college',
    'Studying abroad opportunities',
    'Gap year programs and benefits',
    'Career planning for students',
    'Developing a strong resume and cover letter',
    'Interviewing skills for young professionals',
    'Job search strategies for graduates',
    'Continuing education for professionals',
    'Learning a new skill online',
    'The importance of lifelong learning in the workplace',
    'Professional development opportunities',
    'Mentorship programs for career growth',
    'The future of work and the skills needed',
    'Online learning platforms for professionals',
    'Microlearning and its benefits',
    'Developing leadership skills',
    'Effective communication skills for professionals',
    'Negotiation and conflict resolution skills',
    'Building a personal brand',
    'The importance of networking in your career',
    'Effective time management for professionals',
    'Maintaining work-life balance',
    'Stress management techniques for busy professionals',
  ],
  'Business and Finance': [
    'Starting a business',
    'Business ideas for 2024',
    'How to write a business plan',
    'Funding options for small businesses',
    'Financial management for businesses',
    'Accounting basics for entrepreneurs',
    'Investing for beginners',
    'Stock market basics',
    'Types of investment accounts',
    'Personal finance tips',
    'Saving for retirement',
    'Managing debt',
    'Building credit score',
    'Entrepreneurship resources',
    'Business loans and grants',
    'Business taxes',
    'Marketing strategies for small businesses',
    'E-commerce business guide',
    'Financial literacy for students',
    'International business opportunities',
    'Business ethics and sustainability',
    'The future of work and finance',
    'Financial news and analysis',
    'Top business leaders and investors',
    'Financial planning for your future',
    'Common financial mistakes to avoid',
    'Blockchain and cryptocurrency explained',
    'Real estate investing for beginners',
    'Passive income ideas',
    'Trading strategies for the stock market',
    'Financial technology (Fintech) trends',
    'Cybersecurity for businesses',
    'Business insurance explained',
    'Negotiation and communication skills for business',
    'Mergers and acquisitions (M&A)',
    'Business leadership and management',
    'Work-life balance for entrepreneurs',
    'Business pitch decks and presentations',
    'How to build a strong brand identity',
    'Data analysis for business decisions',
    'Project management for businesses',
    'Customer relationship management (CRM)',
    'Search engine optimization (SEO) for businesses',
    'Social media marketing for businesses',
    'Content marketing strategies',
    'Business networking and communication',
    'Time management for entrepreneurs',
    'Business productivity tips',
    'Delegation and outsourcing strategies',
    'Conflict resolution in the workplace',
    'Remote work and collaboration tools',
    'The future of business jobs',
    'Artificial intelligence (AI) in business',
    'Machine learning for finance',
    'Big data and business analytics',
    'Business case studies and success stories',
    'Business awards and recognition programs',
    'Economic trends and forecasts',
    'Global financial markets',
    'Business psychology and consumer behavior',
  ],
  'Home and Garden': [
    'Modern living room ideas',
    'Kitchen renovation tips on a budget',
    'DIY projects for beginners',
    'Sustainable home decor ideas',
    'Small space living solutions',
    'Choosing the right paint colors',
    'Eco-friendly cleaning products',
    'Organizing and storage hacks',
    'Smart home technology for beginners',
    'Furniture reupholstery tips',
    'How to start a vegetable garden',
    'Best plants for beginners',
    'Container gardening ideas',
    'Attracting pollinators to your garden',
    'Organic gardening techniques',
    'Companion planting guide',
    'Troubleshooting common garden problems',
    'Growing herbs indoors',
    'Building a raised garden bed',
    'Xeriscaping: Water-efficient landscaping',
    'DIY home repairs you can do yourself',
    'Spring cleaning checklist',
    'Carpet cleaning tips',
    'How to maintain your lawn',
    'Winterizing your home',
    'Energy-efficient home improvements',
    'Common plumbing problems and solutions',
    'Basic electrical repairs',
    'Pest control methods for your home',
    "Choosing the right homeowner's insurance",
    'Open floor plan living: Pros and cons',
    'Creating a backyard oasis',
    'Choosing the right houseplants',
    'Pet-friendly home decor ideas',
    'Sustainable gardening practices',
    'Upcycling and repurposing furniture',
    'Outdoor furniture buying guide',
    'Throwing a backyard party',
    'Home safety tips for families',
    'Creating a relaxing home spa atmosphere',
  ],
};
